remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Rizwan's Photography
description: Explore and purchase breathtaking photographs of landscapes, buildings, birds, flowers, wildlife, and nature. High-quality images available for collectors, businesses, designers, and photography enthusiasts worldwide.
github:
  zip_url: http://example.com/download.zip
  another_url: http://cbc.ca/
